[package]
name = "latexbuild"
version = "0.1.0"
authors = ["Zehua-Chen <peterchen06242000@outlook.com>"]
edition = "2018"

[[bin]]
name = "latexbuild"

[lib]
name="latexbuild"
path="src/latexbuild/lib.rs"

[dependencies]
clap = "2.33.0"
json = "0.12.0"
